# model settings
norm_cfg = dict(type='SyncBN', requires_grad=True)
backbone_norm_cfg = dict(type='LN', requires_grad=True)
model = dict(
    type='EncoderDecoder',
    pretrained=None,
    backbone=dict(
        type='DAT',
        img_size=224, patch_size=4, num_classes=1000, expansion=4,
        dim_stem=96, dims=[96, 192, 384, 768], depths=[2, 2, 6, 2], 
        heads=[3, 6, 12, 24], heads_q=[6, 12, 24, 48],
        window_sizes=[7, 7, 7, 7],
        drop_rate=0.0, attn_drop_rate=0.0, drop_path_rate=0.0, 
        strides=[-1,-1,-1,-1],
        offset_range_factor=[1, 2, 3, 4],
        local_orf=[-1, -1, -1, -1],
        local_kv_sizes=[-1, -1, -1, -1],
        offset_pes=[False, False, False, False],
        stage_spec=[['L', 'D'], ['L', 'D'], ['L', 'D', 'L', 'D', 'L', 'D'], ['L', 'D']], 
        groups=[-1, -1, 3, 6],
        use_pes=[False, False, False, False], 
        dwc_pes=[False, False, False, False],
        sr_ratios=[8, 4, 2, 1], 
        lower_lr_kvs={},
        fixed_pes=[False, False, False, False],
        no_offs=[False, False, False, False],
        ns_per_pts=[4, 4, 4, 4],
        use_dwc_mlps=[False, False, False, False],
        use_conv_patches=False,
        ksizes=[9, 7, 5, 3],
        ksize_qnas=[3, 3, 3, 3],
        nqs=[2, 2, 2, 2],
        qna_activation='exp',
        deform_groups=[0, 0, 0, 0],
        nat_ksizes=[3,3,3,3],
        layer_scale_values=[-1,-1,-1,-1],
        use_lpus=[False, False, False, False],
        use_cmt_mlps=[False, False, False, False],
        out_indices=(0, 1, 2, 3),
        use_checkpoint=True
    ),
    decode_head=dict(
        type='UPerHead',
        in_channels=[96, 192, 384, 768],
        in_index=[0, 1, 2, 3],
        pool_scales=(1, 2, 3, 6),
        channels=512,
        dropout_ratio=0.1,
        num_classes=19,
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
    auxiliary_head=dict(
        type='FCNHead',
        in_channels=384,
        in_index=2,
        channels=256,
        num_convs=1,
        concat_input=False,
        dropout_ratio=0.1,
        num_classes=19,
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.4)),
    # model training and testing settings
    train_cfg=dict(),
    test_cfg=dict(mode='whole'))
